### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by mdboom** [davglass/git-travis#4]
After a clean install of `git-travis`:

```
git travis                                                                                                                                           « git · d591ab07285e · wcs/upgrade-4_25 »
Fetching build status for mdboom/astropy:On branch wcs/upgrade-4_25

TypeError: Cannot read property 'id' of undefined
    at /home/mdboom/.npm/lib/node_modules/git-travis/lib/index.js:111:50
    at Array.some (native)
    at /home/mdboom/.npm/lib/node_modules/git-travis/lib/index.js:110:24
    at Request._callback (/home/mdboom/.npm/lib/node_modules/git-travis/node_modules/travis-ci/lib/travis-http.js:34:13)
    at Request.self.callback (/home/mdboom/.npm/lib/node_modules/git-travis/node_modules/travis-ci/node_modules/request/index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/mdboom/.npm/lib/node_modules/git-travis/node_modules/travis-ci/node_modules/request/index.js:886:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/mdboom/.npm/lib/node_modules/git-travis/node_modules/travis-ci/node_modules/request/index.js:837:12)
    at IncomingMessage.emit (events.js:117:20)
```

**Comment by davglass** [comment]
This is fixed in `git-travis@1.0.0`, I never updated this to support the git 2.x change with the output.
